### ISSUE TITLE
Using Jest 29-  after configuring allure:  Test environment jest-circus-allure cannot be found. Make sure the testEnvironment configuration option points to an existing node module

### ISSUE THREAD

**Issue by saritvakrat** [c4lifa/jest-allure-circus#153]
## Describe the bug

Using Jest 29-  after configuring allure:  Test environment jest-circus-allure cannot be found. Make sure the testEnvironment configuration option points to an existing node module

## To Reproduce configure:
1. npm i jest-allure-circus
2.   testRunner: "jest-circus/runner",
3.   testEnvironment: "jest-circus-allure",
4. try to run any test

## Actual behavior
Jest throws and error
` Validation Error:

  Test environment jest-circus-allure cannot be found. Make sure the testEnvironment configuration option points to an existing node module.

  Configuration Documentation:
  https://jestjs.io/docs/configuration`

## Expected behavior

You can run tests and allure without issues

## Screenshots

![image](https://user-images.githubusercontent.com/20379084/223419991-f5f28ab5-5106-4516-88cf-39641b1764b0.png)

Jest version:     "ts-jest": "^29.0.3"
allure version:     "jest-allure-circus": "^1.0.21",

**Comment by KillWolfVlad** [comment]
Test env should be `jest-allure-circus`. Docs is wrong. Look up to my jest config as example in package.json

```json
{
  "jest": {
    "moduleFileExtensions": [
      "ts",
      "js"
    ],
    "resetMocks": true,
    "rootDir": "./",
    "roots": [
      "<rootDir>/src",
      "<rootDir>/test"
    ],
    "setupFilesAfterEnv": [
      "jest-extended/all",
      "./src/main.ts"
    ],
    "testEnvironment": "jest-allure-circus",
    "testEnvironmentOptions": {
      "jiraUrl": "https://jira.example.com/browse/",
      "tmsUrl": "https://allure.example.com/project/1/test-cases/"
    },
    "testRegex": ".*\\.spec\\.ts$",
    "testTimeout": 120000,
    "transform": {
      "^.+\\.ts$": "ts-jest"
    }
  }
}
```

**Comment by c4lifasecondary** [comment]
Fixed. Will be added to 1.0.22.

**Comment by streLer** [comment]
when 1.0.22 planning to release? thanks

**Comment by saritvakrat** [comment]
Works after change thanks
