### ISSUE TITLE
Failed tests are ugly because text has ANSI escape codes

### ISSUE THREAD

**Issue by KillWolfVlad** [c4lifa/jest-allure-circus#44]
## Describe the bug

Failed tests are ugly because text has ANSI escape codes.

## To Reproduce

Create simple test:

```typescript
describe("Simple Test", () => {
  it("must parse docblock", () => {
    /** My test description.
     * @epic Implement addition functionality
     * @tag Accounting
     */

    expect(1).toBe(2);
  });
});
```

## Expected behavior

Error description doesn't contain ANSI escape codes.

## Screenshots

Actual result:

![image](https://user-images.githubusercontent.com/18448635/182533443-6ff66aec-15d2-4cc0-84a9-0e8f5a0cf3cc.png)

Expected result:

![image](https://user-images.githubusercontent.com/18448635/182533519-d8404929-4987-40a3-95e3-9cf3458a31bb.png)

## Additional context

I have this jest packages:
* "jest": "28.1.3"
* "jest-allure-circus": "1.0.15"
* "jest-extended": "3.0.1"
* "ts-jest": "28.0.7"

**Comment by KillWolfVlad** [comment]
I think we need use deleted `strip-ansi` or use unused dependency `ansi_up`.

**Comment by c4lifa** [comment]
@KillWolfVlad test now plz. Thanks.

**Comment by KillWolfVlad** [comment]
It is works. Thank you.

P.S. I think better to use package to strip ansi or move duplicated code to function.
