### ISSUE TITLE
Impossible to use wait-for-expect package

### ISSUE THREAD

**Issue by KillWolfVlad** [c4lifa/jest-allure-circus#48]
## Describe the bug

Test fails when code contains `waitForExpect` statement.

## To Reproduce

Create test:

```typescript
import waitForExpect from "wait-for-expect";

describe("test", () => {
  it("test", async () => {
    await waitForExpect(() => {
      console.log(1);
    });
  });
});
```

## Expected behavior

Test runs without errors.

## Screenshots

![image](https://user-images.githubusercontent.com/18448635/183572654-809b2d5f-5f24-45e5-ba06-d48fd2488ddc.png)

## Additional context

I have this jest packages:
* "jest": "28.1.3"
* "jest-allure-circus": "1.0.17"
* "jest-extended": "3.0.1"
* "ts-jest": "28.0.7"

**Comment by KillWolfVlad** [comment]
This issue should come from original package.

https://github.com/c4lifa/jest-allure-circus/blob/4742b67b3f18d5c72581ba5e342c1cc25ee50234/src/allure-reporter.ts#L315-L316

This code add a new line between `wait_for_` and `expect_1.default`. Source code breaks and prettier fails when try to format it. For me I just deleted this lines. But I think exists more glorious solution.

Maybe we should use original TypeScript code to print it in Allure report?

![image](https://user-images.githubusercontent.com/18448635/183573685-3b0a292e-787c-4428-8960-1b106f6c0cc7.png)

**Comment by c4lifa** [comment]
@KillWolfVlad test in 1.0.18 plz. Thanks for finding issue.

**Comment by KillWolfVlad** [comment]
Test not fail. But code serialization is broken:

![image](https://user-images.githubusercontent.com/18448635/183819699-6ba00c53-4658-4c4a-b133-86ced27eeb28.png)

Because `code` that returns from `extractCodeDetails` is an object.

![image](https://user-images.githubusercontent.com/18448635/183819781-22f521a1-5284-4eea-bb77-60c45b1387fa.png)

I think `extractCodeDetails` should return `code` as string like before.

**Comment by c4lifa** [comment]
@KillWolfVlad should be ok, test now in 1.0.19 plz.

**Comment by KillWolfVlad** [comment]
Works like a charm. Thank you.
